### ISSUE TITLE
training data

### ISSUE THREAD

**Issue by KavyaGujjala** [s14t284/Char-BLSTM-CRF-for-Japanese#4]
what are the wordvectors and charvectors 

Do we need to use IOB2 corpus where both word and character embeddings are given
Can you please help through this?

**Comment by rikeda71** [comment]
In this model, word vectors are pre-train word embeddings, char vectors are pre-train embeddings by characters contained in words.
And, we get input vectors of model to concatenate word vectors and char vectors.

For example, we want to get the vecotr of "a" contained in "apple", concatenating the char vector of "a"  and the word vector of "apple".

This model exec Named Entity Recognition for each character, it is necessary to get vector by this algorithm.

When We use this library, need to prepare a file of the following format.

```
J	Japan	B-LOC
a	Japan	I-LOC
p	Japan	I-LOC
a	Japan	I-LOC
n	Japan	I-LOC
i 	is	O
s	is	O
w	wonderful	O
o	wonderful	O
n	wonderful	O
d	wonderful	O
e	wonderful	O
r	wonderful	O
f	wonderful	O
u	wonderful	O
l	wonderful	O

B	Bob	B-PSN
o	Bob	I-PSN
b	Bob	I-PSN
i	is	O
s	is	O
...
```

Moreover, We prepare a pre-train word embedding and pre-train char embedding. 
Pre-train word embedding can be found by searching the internet, We need to make pre-train char embedding yourself using a method such as word2vec.

This model was reporting high performance for Japanese, I do not recommend using it for other than Japanese.

If you want to know details of this model, please show [S Misawa et al](http://www.aclweb.org/anthology/W17-4114) .

**Comment by KavyaGujjala** [comment]
Thanks for the explanation.

However I'm still not clear on how the training dataset should be given. From what you said I understand that japanese training dataset should be given in the format you have mentioned. And also we need to give pre-train word embedding and pre-train char embedding for the training dataset.

Am I right?

**Comment by rikeda71** [comment]
I'm sorry for the delay in replying your comment.
Your description is perfectly right.

**Comment by tringn** [comment]
hi @s14t284,
Thanks for your great work.
How can I find the training dataset that reproduce your result? 
Thanks

**Comment by rikeda71** [comment]
@tringn
I'm not the author of the paper that proposed this method.
So, I'm sorry if the following answer is wrong.

If you want to reproduce the results in the paper, buy the "[mainichi news paper corpus](http://www.nichigai.co.jp/sales/mainichi/mainichi-data.html)", [BCCWJ](https://pj.ninjal.ac.jp/corpus_center/bccwj/), and [the corpus with extended named entity](https://www.gsk.or.jp/catalog/gsk2014-a/).


As far as I know, free Japanese NER corpuses don't exist.
However, we can make a pseudo Japanese NER corpus using [KWDLC](http://nlp.ist.i.kyoto-u.ac.jp/index.php?KWDLC).
I made a script to make a Japanese NER corpus from KWDLC.
(https://github.com/s14t284/KWDLC2NERDataset)

Please use it if you like.
