### ISSUE TITLE
figure1 cnn kernel size

### ISSUE THREAD

**Issue by xilinniao123** [s14t284/Char-BLSTM-CRF-for-Japanese#7]
thanks for sharing! in figure 1 of paper,how many filters in cnn and each filter size is how

**Comment by rikeda71** [comment]
@hitxujian 
I'm not the author of the paper that proposed this method.
So, I'm sorry if the following answer is wrong.

This method don't use CNN.
Author's proposed model is figure 2 in the paper.
Misawa et al. indicated CNN that is unsuitable for extracting Japanese sub-word information.

By the way, figure 1 model is BiLSTM-CNN-CRF model proposed by Ma et al.
(https://arxiv.org/abs/1603.01354)
